Instructions
Load the dataset and explore the variables.
We will try to predict variable Churn using a logistic regression on variables tenure, SeniorCitizen,MonthlyCharges.
Extract the target variable.
Extract the independent variables and scale them.
Build the logistic regression model.
Evaluate the model.
Even a simple model will give us more than 70% accuracy. Why?
Synthetic Minority Oversampling TEchnique (SMOTE) is an over sampling technique based on nearest neighbors that adds new points between existing points. Apply imblearn.over_sampling.SMOTE to the dataset. Build and evaluate the logistic regression model. Is it there any improvement?
Tomek links are pairs of very close instances, but of opposite classes. Removing the instances of the majority class of each pair increases the space between the two classes, facilitating the classification process. Apply imblearn.under_sampling.TomekLinks to the dataset. Build and evaluate the logistic regression model. Is it there any improvement?

In [7]:
import pandas as pd
import numpy as np
import math
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as ss
from scipy.stats import probplot
from scipy import stats
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import Normalizer

from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
import warnings
warnings.filterwarnings('ignore')

import os
import sys

%matplotlib inline

pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows', None)

data = pd.read_csv('customer_churn.csv')

In [8]:
data.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity OnlineBackup  \
0  No phone service             DSL             No          Yes   
1                No             DSL            Yes           No   
2                No             DSL            Yes          Yes   
3  No phone service             DSL            Yes           No   
4                No     Fiber optic             No           No   

  DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0               No          No          No              No  Month-to-month   
1              Yes          No          No              No        One year   
2               No          No          No              No  Month-to-month   
3              Yes         Yes          No              No        One year   
4               No          No          No              No  Month-to-month   

  PaperlessBilling              PaymentMethod  MonthlyCharges TotalCharges  \
0              Yes           Electronic check           29.85        29.85   
1               No               Mailed check           56.95       1889.5   
2              Yes               Mailed check           53.85       108.15   
3               No  Bank transfer (automatic)           42.30      1840.75   
4              Yes           Electronic check           70.70       151.65   

  Churn  
0    No  
1    No  
2   Yes  
3    No  
4   Yes

In [9]:
counts = data['Churn'].value_counts()
counts

No     5174
Yes    1869
Name: Churn, dtype: int64

In [4]:
#numericData = churnData[['tenure', 'SeniorCitizen','MonthlyCharges']]
#Y = pd.DataFrame(data=churnData, columns=['Churn'])
#transformer = StandardScaler().fit(churnData[['tenure','SeniorCitizen','MonthlyCharges']])
#scaled_x = transformer.transform(churnData[['tenure','SeniorCitizen','MonthlyCharges']])
#classification = LogisticRegression(random_state=0, solver='lbfgs',
#                        multi_class='ovr').fit(scaled_x, churnData['Churn'])
#classification.score(scaled_x, churnData['Churn'])

In [5]:
#counts = churnData['Churn'].value_counts()
#yes = churnData[churnData['Churn']=='Yes'].sample(counts[0], replace=True)
#no = churnData[churnData['Churn']=='No']
#data = pd.concat([yes,no], axis=0)
#data = data.sample(frac=1)
#data['Churn'].value_counts()

In [11]:
#1st attempt - running the model on imbalanced data
X = data[['tenure', 'SeniorCitizen','MonthlyCharges']]
transformer = StandardScaler().fit(X)
X = transformer.transform(X)
classification = LogisticRegression(random_state=0, solver='lbfgs',
                        multi_class='ovr').fit(X, data['Churn'])
classification.score(X, data['Churn'])

0.7911401391452506

In [12]:
pip install imblearn

Note: you may need to restart the kernel to use updated packages.


In [20]:
# 2nd attempt with SMOTE
from imblearn.over_sampling import SMOTE
smote = SMOTE()
X = churnData[['tenure', 'SeniorCitizen','MonthlyCharges']]
transformer = StandardScaler().fit(X)
X = transformer.transform(X)
y = churnData['Churn']
X_sm, y_sm = smote.fit_sample(X, y)
y_sm.value_counts()

Yes    5174
No     5174
Name: Churn, dtype: int64

In [21]:
#standardizing data before running the model
X = data[['tenure', 'SeniorCitizen','MonthlyCharges']]
y = data[['Churn']]
transformer = StandardScaler().fit(X)
X = transformer.transform(X)

In [22]:
print(X)

[[-1.27744458 -0.43991649 -1.16032292]
 [ 0.06632742 -0.43991649 -0.25962894]
 [-1.23672422 -0.43991649 -0.36266036]
 ...
 [-0.87024095 -0.43991649 -1.1686319 ]
 [-1.15528349  2.27315869  0.32033821]
 [ 1.36937906 -0.43991649  1.35896134]]


In [30]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=100)

In [31]:
classification = LogisticRegression(random_state=0, solver='lbfgs',
                        multi_class='ovr').fit(X, data['Churn'])
classification.score(X, data['Churn'])

0.7911401391452506

In [32]:
predictions = classification

In [34]:
#predictions = classification.predict(X)
#print(prediction)

In [35]:
# 3rd with TomekLinks
from imblearn.under_sampling import TomekLinks

tl = TomekLinks('majority')
X_tl, y_tl = tl.fit_sample(X, y)
y_tl.value_counts()

Churn
No       4694
Yes      1869
dtype: int64

In [36]:
model = LogisticRegression(random_state=0, solver='lbfgs',
                        multi_class='ovr').fit(X_tl, y_tl)

NameError: name 'prediction' is not defined